### ISSUE TITLE
Gradient - Magazine Submissions

### ISSUE THREAD

**Issue by jesparent** [CognitionFutures/admin#15]
- [ ] Neuromatch

- [ ] Summer of Learning

- [ ] Cybernetics vs Baes

- [ ] norbert wiener quote / future / robot slaves / ALIFE 2021
